const items = [
"Apple",
"Avocado",
"Grapes",
"Banana",
"warm water with juice of half a lime and honey",
"warm water with Apple cider viniger",
"warm water with juice of 2 amla and honey",
"warm water with 2 teaspoons fenugreek seeds soaked overnight",
"Green tea with honey",
"Green tea",
"Black coffee witout sugar",
"Black tea",
"Coffee with thick milk",
"Ice cream",
"Lessi",
"Yogurt",
"Milk",
"Skimmed milk with pinch of turmaric",
"Idle-millet",
"Idle",
"Tofu",
"Paneer",
"Mini bowl sambar",
"Mini bowl Veg salad",
"Mini bowl fruit salad",
"Chutney-coconut",
"Chutney-Garlic",
"Chutney-Pudhina",
"Chutney-Malli",
"Chutney-tomotto",
"Chutney-onion",
"Peanut butter 1 spoon",
"Honey 1 spoon",
"Curd 1 small cup",
"Buttermilk 200 ml",
"Ragi balls",
"Sambar",
"Rasam",
"Poriyal",
"Spinach",
"Marie biscuits",
"Nutri choice biscut",
"Wheat rusk",
"Tea cake",
"Plum cake",
"Chappathi or roti",
"rava dosa",
"Oothappam",
"Onion dosa",
"Wheat dosa",
"Wheat Upma",
"Pongal",
"Wheat rava dosa",
"almomd-overnight socked",
"Fig-overnight socked",
"Grapes dry-overnight socked",
"Cashew-overnight socked",
"Dates",
"Pistha",
"Rice-white",
"Rice-red",
"Rice-brown",
"Cucumber",
"carrot",
"tomotto",
"Beans",
"Cabbage",
"Broccolli",
"peanut-boiled 1 small bowl",
"Channa-boiled 1 small bowl",
"moong-boiled 1 small bowl",
"Rajma-boiled 1 small bowl",
"Soya chunk-boiled 1 small bowl",
"daal boiled 1 cup",
"Honey",
"Ghee",
"Juice-Watermelon without sugar without milk",
"Juice-pomogranate without sugar without milk",
"Juice-orange without sugar without milk",
"Juice-Muskmelon without sugar without milk",
"Lemon-Watermelon without sugar without milk",
"Juice-Grapes without sugar without milk",
"Juice-Beetroot without sugar without milk",
"Kiwi",
"sprouts salad 1 cup",
"multigrain atta parotas",
"Quinoa upma",
"popcorn 100 gram",
"fish",
"Chicken leg",
"Chicken breast",
"Beef",
"Red meat any",
"Mutton",
"Idiyappam",
"dark chocolate",
"mushroom",
"prawn",
"Crab",
"Veg-Bitter gourd",
"Veg-pumpkin",
"Veg-green banana",
"Veg-bottle gourd",
"Veg-ridge gourd",
"Veg-radish",
"Veg-peas",
"papaya",
"orange",
"Mango",
"jackfruit",
"cheese",
"butter",
"Olive oil",
"sunflower seed",
"peanut butter",
"Mayonnaise",
"chia seeds",
"flaxseed",
"egg whites",
"egg full",
"oats masala",
"Sweet potato",
"Whey",
"Weight gainer protein shake",
"protein shake - milk 100 ml + oats 50 gram+ banana 1 + egg 3 + peanut butter 1 spoon  ice cubes ",
"Wheat bread toasted with 1 spoon peanut butter with 1 spoon honey stuffed with half banana",
"potato",
"Tapioca root",
"Gulfi",
  ];
  